<a href="https://colab.research.google.com/github/saikritikaboorla/Nasscom/blob/main/Assignment_6-EV-Battery_5E0_NASSCOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Smart Electric Vehicle Battery Performance Analysis**

In [52]:
import pandas as pd

data = {
    'Time (h)': [0, 1, 2, 3, 4, 5],
    'Temperature (°C)': [32, 35, 38, 40, 42, 45],
    'Voltage (V)': [400, 395, 390, 385, 380, 375],
    'Current (A)': [20, 22, 25, 28, 30, 32],
    'Charge (%)': [95, 88, 80, 70, 60, 48]
}

df = pd.DataFrame(data)

display(df)

,Time (h),Temperature (°C),Voltage (V),Current (A),Charge (%)
0,0,32,400,20,95
1,1,35,395,22,88
2,2,38,390,25,80
3,3,40,385,28,70
4,4,42,380,30,60
5,5,45,375,32,48


Task 1 — Analysis Using Python Basics
Store the given sensor readings using appropriate Python data structures, then perform the following tasks.
1. Display the sensor readings
Use a for loop to display all battery readings.
2. Identify high temperature
Apply the following condition:
  If  T > 40 °C  
Display: “High Temperature Alert”
Otherwise, display: “Temperature Normal”
3. Identify low battery
Apply the following condition:
  If  C < 50 %  
Display: “Low Battery Alert”
Otherwise, display: “Battery Charge Normal”
4. Create a function
Create a function battery_status(charge) that returns a status based on:
           High,     C > 70
Status =   Medium,   50 ≤ C ≤ 70
           Low,      C < 50


In [53]:
sensor_readings = []
for i in range(len(data['Time (h)'])):
    sensor_readings.append({
        'time': data['Time (h)'][i],
        'temperature': data['Temperature (°C)'][i],
        'voltage': data['Voltage (V)'][i],
        'current': data['Current (A)'][i],
        'battery_charge': data['Charge (%)'][i]
    })

print("Sensor readings prepared for basic Python analysis:")
for reading in sensor_readings:
    print(reading)

Sensor readings prepared for basic Python analysis:
{'time': 0, 'temperature': 32, 'voltage': 400, 'current': 20, 'battery_charge': 95}
{'time': 1, 'temperature': 35, 'voltage': 395, 'current': 22, 'battery_charge': 88}
{'time': 2, 'temperature': 38, 'voltage': 390, 'current': 25, 'battery_charge': 80}
{'time': 3, 'temperature': 40, 'voltage': 385, 'current': 28, 'battery_charge': 70}
{'time': 4, 'temperature': 42, 'voltage': 380, 'current': 30, 'battery_charge': 60}
{'time': 5, 'temperature': 45, 'voltage': 375, 'current': 32, 'battery_charge': 48}


### 1. Display all battery readings

In [54]:
print("Battery Readings:")
for reading in sensor_readings:
    print(f"  {reading['battery_charge']}% Charge")

Battery Readings:
  95% Charge
  88% Charge
  80% Charge
  70% Charge
  60% Charge
  48% Charge


### 2. Identify high temperature

In [55]:
print("\nTemperature Status:")
for i, reading in enumerate(sensor_readings):
    if reading['temperature'] > 40:
        print(f"  Sensor {i+1}: High Temperature Alert (T = {reading['temperature']} °C)")
    else:
        print(f"  Sensor {i+1}: Temperature Normal (T = {reading['temperature']} °C)")


Temperature Status:
  Sensor 1: Temperature Normal (T = 32 °C)
  Sensor 2: Temperature Normal (T = 35 °C)
  Sensor 3: Temperature Normal (T = 38 °C)
  Sensor 4: Temperature Normal (T = 40 °C)
  Sensor 5: High Temperature Alert (T = 42 °C)
  Sensor 6: High Temperature Alert (T = 45 °C)


### 3. Identify low battery

In [56]:
print("\nBattery Charge Status:")
for i, reading in enumerate(sensor_readings):
    if reading['battery_charge'] < 50:
        print(f"  Sensor {i+1}: Low Battery Alert (C = {reading['battery_charge']} %)")
    else:
        print(f"  Sensor {i+1}: Battery Charge Normal (C = {reading['battery_charge']} %)")


Battery Charge Status:
  Sensor 1: Battery Charge Normal (C = 95 %)
  Sensor 2: Battery Charge Normal (C = 88 %)
  Sensor 3: Battery Charge Normal (C = 80 %)
  Sensor 4: Battery Charge Normal (C = 70 %)
  Sensor 5: Battery Charge Normal (C = 60 %)
  Sensor 6: Low Battery Alert (C = 48 %)


### 4. Create a function `battery_status(charge)`

In [57]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif 50 <= charge <= 70:
        return "Medium"
    else:
        return "Low"

print("\nBattery Status Function Test:")
for i, reading in enumerate(sensor_readings):
    status = battery_status(reading['battery_charge'])
    print(f"  Sensor {i+1}: Charge {reading['battery_charge']}%, Status: {status}")


Battery Status Function Test:
  Sensor 1: Charge 95%, Status: High
  Sensor 2: Charge 88%, Status: High
  Sensor 3: Charge 80%, Status: High
  Sensor 4: Charge 70%, Status: Medium
  Sensor 5: Charge 60%, Status: Medium
  Sensor 6: Charge 48%, Status: Low


Task 2 — Analysis Using NumPy
Convert the battery data into a NumPy array. Assume the data matrix is:
        ┌ 32   400   20   95 ┐
        │ 35   395   22   88 │
  D  =  │ 38   390   25   80 │
        │ 40   385   28   70 │
        │ 42   380   30   60 │
        └ 45   375   32   48 ┘
where the columns represent: [ Temperature,  Voltage,  Current,  Charge ]
Perform the following operations:
1. Find the shape of the array
Determine the number of rows and the number of columns.
2. Calculate the average of each parameter
For example, the average temperature is:
  T̄  =  (T₁ + T₂ + T₃ + T₄ + T₅ + T₆) / 6  
Similarly, calculate V̄ (average voltage), Ī (average current), and C̄ (average charge).
3. Find the maximum and minimum temperature
Determine T_max and T_min.
4. Extract the voltage column
Extract the column vector:
      ┌ 400 ┐
      │ 395 │
V  =  │ 390 │
      │ 385 │
      │ 380 │
      └ 375 ┘
5. Identify high-temperature readings
Find all rows satisfying:
  T > 40 °C  
6. Identify low battery readings
Find all rows satisfying:
  C < 50 %  


In [58]:
import numpy as np

battery_data_np = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])

print("Battery Data NumPy Array:")
print(battery_data_np)

Battery Data NumPy Array:
[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


### 1. Find the shape of the array

In [59]:
array_shape = battery_data_np.shape
print(f"Shape of the array (rows, columns): {array_shape}")

Shape of the array (rows, columns): (6, 4)


### 2. Calculate the average of each parameter

In [60]:
averages = np.mean(battery_data_np, axis=0)

print(f"Average Temperature: {averages[0]:.2f} °C")
print(f"Average Voltage: {averages[1]:.2f} V")
print(f"Average Current: {averages[2]:.2f} A")
print(f"Average Charge: {averages[3]:.2f} %")

Average Temperature: 38.67 °C
Average Voltage: 387.50 V
Average Current: 26.17 A
Average Charge: 73.50 %


### 3. Find the maximum and minimum temperature

In [61]:
max_temp = np.max(battery_data_np[:, 0])
min_temp = np.min(battery_data_np[:, 0])

print(f"Maximum Temperature (T_max): {max_temp} °C")
print(f"Minimum Temperature (T_min): {min_temp} °C")

Maximum Temperature (T_max): 45 °C
Minimum Temperature (T_min): 32 °C


### 4. Extract the voltage column

In [62]:
voltage_column = battery_data_np[:, 1]

print("Voltage Column:")
print(voltage_column)

Voltage Column:
[400 395 390 385 380 375]


### 5. Identify high-temperature readings

In [63]:
high_temp_readings = battery_data_np[battery_data_np[:, 0] > 40]

print("High Temperature Readings (T > 40 °C):")
print(high_temp_readings)

High Temperature Readings (T > 40 °C):
[[ 42 380  30  60]
 [ 45 375  32  48]]


### 6. Identify low battery readings

In [64]:
low_battery_readings = battery_data_np[battery_data_np[:, 3] < 50]

print("Low Battery Readings (C < 50 %):")
print(low_battery_readings)

Low Battery Readings (C < 50 %):
[[ 45 375  32  48]]


Task 3 — Analysis Using Linear Algebra
The company uses temperature and current to calculate a simplified Battery Stress Index.
Let the transformation matrix be:
      ┌ 2   1 ┐
A  =  │       │
      └ 1   3 ┘
Consider the sensor input:
      ┌ T ┐     ┌ 40 ┐
X  =  │   │  =  │    │
      └ I ┘     └ 25 ┘
The output is calculated as:
  Y  =  A X  
Therefore:
      ┌ 2   1 ┐   ┌ 40 ┐
Y  =  │       │ × │    │
      └ 1   3 ┘   └ 25 ┘
Students must calculate the resulting vector Y.
Additional Linear Algebra Tasks
For the matrix A above, find:
1. Transpose
  Aᵀ  
2. Determinant
  det(A)  
3. Inverse
A⁻¹, if the inverse exists.
Solving a System of Equations
The engineers need to determine two unknown battery parameters x and y. The equations are:
  2x + y = 100  
  x + 3y = 120  
Write the equations in matrix form:
  A X = B  
where:
      ┌ 2   1 ┐        ┌ x ┐        ┌ 100 ┐
A  =  │       │   X =  │   │   B  =  │     │
      └ 1   3 ┘        └ y ┘        └ 120 ┘
Students must solve for x and y using NumPy.


In [65]:
import numpy as np

A = np.array([
    [2, 1],
    [1, 3]
])

X = np.array([
    [40],
    [25]
])

print("Matrix A:")
print(A)
print("\nVector X:")
print(X)

Matrix A:
[[2 1]
 [1 3]]

Vector X:
[[40]
 [25]]


In [66]:
Y = np.dot(A, X)

print("Resulting Vector Y:")
print(Y)

Resulting Vector Y:
[[105]
 [115]]


### 1. Transpose of A

In [67]:
A_transpose = A.T

print("Transpose of Matrix A (Aᵀ):")
print(A_transpose)

Transpose of Matrix A (Aᵀ):
[[2 1]
 [1 3]]


### 2. Determinant of A

In [68]:
A_determinant = np.linalg.det(A)

print("Determinant of Matrix A (det(A)):")
print(A_determinant)

Determinant of Matrix A (det(A)):
5.000000000000001


### 3. Inverse of A

In [69]:
A_inverse = np.linalg.inv(A)

print("Inverse of Matrix A (A⁻¹):")
print(A_inverse)

Inverse of Matrix A (A⁻¹):
[[ 0.6 -0.2]
 [-0.2  0.4]]


### Solving a System of Equations

In [70]:
A_eq = np.array([
    [2, 1],
    [1, 3]
])

B_eq = np.array([
    [100],
    [120]
])

solution = np.linalg.solve(A_eq, B_eq)

print("Solution for the system of equations (x, y):")
print(solution)

Solution for the system of equations (x, y):
[[36.]
 [28.]]


Task 4 — Analysis Using Calculus
The battery charge is modeled as a function of time:
  C(t)  =  100 − 2t − ½t²  
where C(t) is the battery charge percentage and t is the time in hours.
1. Find the rate of change of battery charge
The rate at which the battery charge changes is given by dC/dt. Differentiate C(t) and determine dC/dt.
2. Calculate the discharge rate
Find the discharge rate at t = 2 and t = 5, that is, calculate:
  dC/dt  at  t = 2      and      dC/dt  at  t = 5  
3. Interpret the result
Based on the values of dC/dt, determine whether the battery is losing charge:
At a constant rate
At an increasing rate
At a decreasing rate


### 1. Find the rate of change of battery charge

In [71]:
from sympy import symbols, diff

t = symbols('t')
C = 100 - 2*t - (1/2)*t**2
dC_dt = diff(C, t)

print(f"The rate of change of battery charge, dC/dt, is: {dC_dt}")

The rate of change of battery charge, dC/dt, is: -1.0*t - 2


### 2. Calculate the discharge rate

In [72]:
discharge_rate_t2 = dC_dt.subs(t, 2)
discharge_rate_t5 = dC_dt.subs(t, 5)

print(f"Discharge rate at t = 2 hours: {discharge_rate_t2} %/hour")
print(f"Discharge rate at t = 5 hours: {discharge_rate_t5} %/hour")

Discharge rate at t = 2 hours: -4.00000000000000 %/hour
Discharge rate at t = 5 hours: -7.00000000000000 %/hour
