<a href="https://colab.research.google.com/github/saikritikaboorla/Nasscom/blob/main/Assignment_3_5E0_NASSCOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


def section_header(title):
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


# ---------------------------------------------------------------
# 1. Creating Matrices and Vectors
# ---------------------------------------------------------------
def example_create_arrays():
    section_header("1. Creating Matrices and Vectors")

    v = np.array([1, 2, 3])
    A = np.array([[1, 2], [3, 4]])
    I = np.eye(3)          # identity matrix
    Z = np.zeros((2, 3))
    O = np.ones((3, 2))

    print("Vector v:\n", v)
    print("Matrix A:\n", A)
    print("Identity I:\n", I)
    print("Zeros Z:\n", Z)
    print("Ones O:\n", O)


# Exercises:
# 1a. Create a 4x4 identity matrix and print it.
# 1b. Create a 3x3 matrix filled with the number 7 (hint: np.full).
# 1c. Create a vector of 10 evenly spaced numbers between 0 and 1
#     (hint: np.linspace).
#
# --- your code here ---
print("\n--- Exercises 1 ---")
# 1a. Create a 4x4 identity matrix and print it.
identity_4x4 = np.eye(4)
print("1a. 4x4 Identity Matrix:\n", identity_4x4)

# 1b. Create a 3x3 matrix filled with the number 7.
matrix_3x3_seven = np.full((3, 3), 7)
print("1b. 3x3 Matrix filled with 7:\n", matrix_3x3_seven)

# 1c. Create a vector of 10 evenly spaced numbers between 0 and 1.
linspace_vector = np.linspace(0, 1, 10)
print("1c. Vector of 10 evenly spaced numbers between 0 and 1:\n", linspace_vector)


# ---------------------------------------------------------------
# 2. Matrix Multiplication
# ---------------------------------------------------------------
def example_matrix_multiplication():
    section_header("2. Matrix Multiplication")

    A = np.array([[1, 2], [3, 4]])
    B = np.array([[5, 6], [7, 8]])

    elementwise = A * B          # element-wise multiplication
    matmul_operator = A @ B      # matrix multiplication (preferred)
    matmul_function = np.matmul(A, B)
    dot_function = np.dot(A, B)

    print("A:\n", A)
    print("B:\n", B)
    print("Element-wise A*B:\n", elementwise)
    print("Matrix mult A@B:\n", matmul_operator)
    print("np.matmul(A, B):\n", matmul_function)
    print("np.dot(A, B):\n", dot_function)


# Exercises:
# 2a. Given A = [[2, 0], [0, 2]] and B = [[1, 2], [3, 4]], compute A@B
#     by hand, then verify with NumPy.
# 2b. Multiply a 3x2 matrix by a 2x4 matrix. What shape is the result?
# 2c. Explain (in a comment) why A*B and A@B give different results.
#
# --- your code here ---
print("\n--- Exercises 2 ---")
# 2a. Given A = [[2, 0], [0, 2]] and B = [[1, 2], [3, 4]], compute A@B
#     by hand, then verify with NumPy.
A_2a = np.array([[2, 0], [0, 2]])
B_2a = np.array([[1, 2], [3, 4]])
result_2a = A_2a @ B_2a
print("2a. A@B for given matrices:\n", result_2a)

# 2b. Multiply a 3x2 matrix by a 2x4 matrix. What shape is the result?
matrix_3x2 = np.array([[1, 2], [3, 4], [5, 6]])
matrix_2x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
result_2b = matrix_3x2 @ matrix_2x4
print("2b. Product of 3x2 and 2x4 matrices:\n", result_2b)
print("    Shape of the result:\n", result_2b.shape) # Result should be 3x4

# 2c. Explain (in a comment) why A*B and A@B give different results.
# A*B performs element-wise multiplication (Hadamard product), meaning it multiplies
# corresponding elements in two arrays of the same shape. For example, the element
# at (0,0) in the result is the product of element A(0,0) and B(0,0).
# A@B performs matrix multiplication, which follows the rules of linear algebra.
# For matrix multiplication, the number of columns in the first matrix must equal
# the number of rows in the second matrix. The elements of the resulting matrix
# are computed as dot products of rows from the first matrix and columns from the second.


# ---------------------------------------------------------------
# 3. Transpose
# ---------------------------------------------------------------
def example_transpose():
    section_header("3. Transpose")

    A = np.array([[1, 2, 3], [4, 5, 6]])
    print("A:\n", A)
    print("A.T (transpose):\n", A.T)
    print("np.transpose(A):\n", np.transpose(A))


# Exercises:
# 3a. Create a 3x5 matrix and confirm its transpose has shape (5, 3).
# 3b. Verify that (A @ B).T equals B.T @ A.T for two matrices A, B.
#
# --- your code here ---
print("\n--- Exercises 3 ---")
# 3a. Create a 3x5 matrix and confirm its transpose has shape (5, 3).
matrix_3x5 = np.arange(1, 16).reshape(3, 5)
print("3a. Original 3x5 matrix:\n", matrix_3x5)
matrix_3x5_t = matrix_3x5.T
print("    Transpose of 3x5 matrix:\n", matrix_3x5_t)
print("    Shape of transpose:\n", matrix_3x5_t.shape) # Should be (5, 3)

# 3b. Verify that (A @ B).T equals B.T @ A.T for two matrices A, B.
A_3b = np.array([[1, 2], [3, 4], [5, 6]]) # 3x2 matrix
B_3b = np.array([[7, 8, 9], [10, 11, 12]]) # 2x3 matrix

left_side = (A_3b @ B_3b).T
right_side = B_3b.T @ A_3b.T

print("3b. (A @ B).T:\n", left_side)
print("    B.T @ A.T:\n", right_side)
print("    Are they equal?", np.array_equal(left_side, right_side))


# ---------------------------------------------------------------
# 4. Determinant
# ---------------------------------------------------------------
def example_determinant():
    section_header("4. Determinant")

    A = np.array([[4, 2], [7, 6]])
    det = np.linalg.det(A)
    print("A:\n", A)
    print("Determinant of A:", det)


# Exercises:
# 4a. Compute the determinant of a 3x3 matrix of your choice.
# 4b. Create a singular (non-invertible) matrix and show its
#     determinant is (approximately) zero.
#
# --- your code here ---
print("\n--- Exercises 4 ---")
# 4a. Compute the determinant of a 3x3 matrix of your choice.
matrix_3x3_det = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det_4a = np.linalg.det(matrix_3x3_det)
print("4a. Matrix:\n", matrix_3x3_det)
print("    Determinant:\n", det_4a)

# 4b. Create a singular (non-invertible) matrix and show its
#     determinant is (approximately) zero.
singular_matrix = np.array([[1, 2], [2, 4]]) # Row 2 is 2 * Row 1
det_singular = np.linalg.det(singular_matrix)
print("4b. Singular Matrix:\n", singular_matrix)
print("    Determinant (should be approx 0):\n", det_singular)


# ---------------------------------------------------------------
# 5. Matrix Inverse
# ---------------------------------------------------------------
def example_inverse():
    section_header("5. Matrix Inverse")

    A = np.array([[4, 7], [2, 6]])
    A_inv = np.linalg.inv(A)
    identity_check = A @ A_inv

    print("A:\n", A)
    print("Inverse of A:\n", A_inv)
    print("A @ A_inv (should be identity):\n", identity_check)


# Exercises:
# 5a. Try to invert a singular matrix and observe the error NumPy
#     raises (hint: wrap in try/except).
# 5b. Verify that (A_inv)_inv == A for a matrix of your choice.
#
# --- your code here ---
print("\n--- Exercises 5 ---")
# 5a. Try to invert a singular matrix and observe the error NumPy
#     raises (hint: wrap in try/except).
singular_matrix_5a = np.array([[1, 2], [2, 4]])
print("5a. Attempting to invert singular matrix:\n", singular_matrix_5a)
try:
    np.linalg.inv(singular_matrix_5a)
except np.linalg.LinAlgError as e:
    print(f"    Caught expected error: {e}")

# 5b. Verify that (A_inv)_inv == A for a matrix of your choice.
A_5b = np.array([[3, 1], [2, 5]])
A_5b_inv = np.linalg.inv(A_5b)
A_5b_inv_inv = np.linalg.inv(A_5b_inv)
print("5b. Original matrix A:\n", A_5b)
print("    (A_inv)_inv:\n", A_5b_inv_inv)
print("    Are they approximately equal?", np.allclose(A_5b, A_5b_inv_inv))


# ---------------------------------------------------------------
# 6. Solving Systems of Linear Equations
# ---------------------------------------------------------------
def example_solve_linear_system():
    section_header("6. Solving Linear Systems (Ax = b)")

    # 2x + 3y = 8
    # 5x + 4y = 13
    A = np.array([[2, 3], [5, 4]])
    b = np.array([8, 13])

    x = np.linalg.solve(A, b)
    print("A:\n", A)
    print("b:", b)
    print("Solution x:", x)
    print("Check A @ x == b:", np.allclose(A @ x, b))


# Exercises:
# 6a. Solve the system:
#       x + y + z = 6
#       2y + 5z = -4
#       2x + 5y - z = 27
# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
#
# --- your code here ---
print("\n--- Exercises 6 ---")
# 6a. Solve the system:
#       x + y + z = 6
#       0x + 2y + 5z = -4
#       2x + 5y - z = 27
A_6a = np.array([[1, 1, 1], [0, 2, 5], [2, 5, -1]])
b_6a = np.array([6, -4, 27])
x_6a = np.linalg.solve(A_6a, b_6a)
print("6a. Coefficient Matrix A:\n", A_6a)
print("    Constant Vector b:\n", b_6a)
print("    Solution x (x, y, z):\n", x_6a)
print("    Check A @ x == b:", np.allclose(A_6a @ x_6a, b_6a))

# 6b. Compare np.linalg.solve(A, b) with computing
#     np.linalg.inv(A) @ b. Which is generally preferred, and why?
# np.linalg.solve(A, b) is generally preferred over np.linalg.inv(A) @ b.
# This is because `solve` uses more numerically stable and efficient algorithms
# (like LU decomposition) to directly find the solution without explicitly
# computing the inverse. Calculating the inverse first can be computationally
# more expensive and prone to greater numerical errors, especially for large
# or ill-conditioned matrices.


# ---------------------------------------------------------------
# 7. Eigenvalues and Eigenvectors
# ---------------------------------------------------------------
def example_eigen():
    section_header("7. Eigenvalues and Eigenvectors")

    A = np.array([[4, -2], [1, 1]])
    eigenvalues, eigenvectors = np.linalg.eig(A)

    print("A:\n", A)
    print("Eigenvalues:", eigenvalues)
    print("Eigenvectors (columns):\n", eigenvectors)


# Exercises:
# 7a. Verify A @ v == lambda * v for each eigenvalue/eigenvector pair.
# 7b. Find the eigenvalues of a diagonal matrix and explain the
#     pattern you notice.
#
# --- your code here ---
print("\n--- Exercises 7 ---")
# 7a. Verify A @ v == lambda * v for each eigenvalue/eigenvector pair.
A_7a = np.array([[4, -2], [1, 1]])
eigenvalues_7a, eigenvectors_7a = np.linalg.eig(A_7a)

print("7a. Original Matrix A:\n", A_7a)
for i in range(len(eigenvalues_7a)):
    eigenvalue = eigenvalues_7a[i]
    eigenvector = eigenvectors_7a[:, i]
    lhs = A_7a @ eigenvector
    rhs = eigenvalue * eigenvector
    print(f"    Eigenvalue {i+1}: {eigenvalue:.4f}")
    print(f"    Eigenvector {i+1}: {eigenvector}")
    print(f"    A @ v: {lhs}")
    print(f"    lambda * v: {rhs}")
    print(f"    Are they approximately equal? {np.allclose(lhs, rhs)}\n")

# 7b. Find the eigenvalues of a diagonal matrix and explain the
#     pattern you notice.
diagonal_matrix = np.array([[1, 0, 0], [0, 5, 0], [0, 0, 9]])
eigenvalues_diag, _ = np.linalg.eig(diagonal_matrix)
print("7b. Diagonal Matrix:\n", diagonal_matrix)
print("    Eigenvalues:\n", eigenvalues_diag)
# Pattern: The eigenvalues of a diagonal matrix are simply the diagonal entries
# of the matrix itself.


# ---------------------------------------------------------------
# 8. Norms (vector and matrix length/magnitude)
# ---------------------------------------------------------------
def example_norms():
    section_header("8. Norms")

    v = np.array([3, 4])
    l2_norm = np.linalg.norm(v)          # Euclidean norm
    l1_norm = np.linalg.norm(v, ord=1)   # Manhattan norm

    print("v:", v)
    print("L2 norm (Euclidean):", l2_norm)
    print("L1 norm (Manhattan):", l1_norm)


# Exercises:
# 8a. Compute the L2 norm of a 5-dimensional vector.
# 8b. Normalize a vector (divide by its own norm) so its length is 1,
#     and verify the result with np.linalg.norm.
#
# --- your code here ---
print("\n--- Exercises 8 ---")
# 8a. Compute the L2 norm of a 5-dimensional vector.
vector_5d = np.array([1, 2, 3, 4, 5])
l2_norm_5d = np.linalg.norm(vector_5d)
print("8a. 5-dimensional vector:\n", vector_5d)
print("    L2 norm:\n", l2_norm_5d)

# 8b. Normalize a vector (divide by its own norm) so its length is 1,
#     and verify the result with np.linalg.norm.
vector_to_normalize = np.array([3, 0, 4])
norm_vec = np.linalg.norm(vector_to_normalize)
normalized_vector = vector_to_normalize / norm_vec
print("8b. Original vector:\n", vector_to_normalize)
print("    Normalized vector:\n", normalized_vector)
print("    Norm of normalized vector:\n", np.linalg.norm(normalized_vector))


# ---------------------------------------------------------------
# 9. Rank of a Matrix
# ---------------------------------------------------------------
def example_rank():
    section_header("9. Matrix Rank")

    full_rank = np.array([[1, 2], [3, 4]])
    deficient_rank = np.array([[1, 2], [2, 4]])  # second row = 2 * first row

    print("Full-rank matrix:\n", full_rank, "-> rank =", np.linalg.matrix_rank(full_rank))
    print("Rank-deficient matrix:\n", deficient_rank, "-> rank =", np.linalg.matrix_rank(deficient_rank))


# Exercises:
# 9a. Construct a 4x4 matrix with rank 2.
# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
#
# --- your code here ---
print("\n--- Exercises 9 ---")
# 9a. Construct a 4x4 matrix with rank 2.
# A simple way is to create two linearly independent rows/columns
# and then make other rows/columns linear combinations of these two.
r1 = np.array([1, 0, 0, 0])
r2 = np.array([0, 1, 0, 0])
r3 = 2 * r1 # A_matrix_rank = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [2, 0, 0, 0], [0, 3, 0, 0]])
r4 = 3 * r2
A_matrix_rank = np.array([r1, r2, r3, r4])
print("9a. 4x4 Matrix with rank 2:\n", A_matrix_rank)
print("    Rank:\n", np.linalg.matrix_rank(A_matrix_rank))

# 9b. Explain (in a comment) the relationship between rank and
#     whether a matrix is invertible.
# A square matrix is invertible (non-singular) if and only if its rank
# is equal to its dimension (i.e., a full-rank matrix). If the rank is
# less than its dimension (rank-deficient), the matrix is singular and
# not invertible. This is because a full-rank matrix implies that all
# its rows (or columns) are linearly independent, which is a requirement
# for an inverse to exist.


# ---------------------------------------------------------------
# 10. Singular Value Decomposition (SVD)
# ---------------------------------------------------------------
def example_svd():
    section_header("10. Singular Value Decomposition (SVD)")

    A = np.array([[1, 2], [3, 4], [5, 6]])
    U, S, Vt = np.linalg.svd(A)

    print("A:\n", A)
    print("U:\n", U)
    print("Singular values S:", S)
    print("V^T:\n", Vt)

    # Reconstruct A from U, S, Vt to verify decomposition
    S_full = np.zeros(A.shape)
    np.fill_diagonal(S_full, S)
    A_reconstructed = U @ S_full @ Vt
    print("Reconstructed A:\n", A_reconstructed)


# Exercises:
# 10a. Reconstruct A from its SVD components and confirm it matches
#      the original (use np.allclose).
# 10b. Use SVD to compute a low-rank approximation of A by keeping
#      only the largest singular value. How close is it to A?
#
# --- your code here ---
print("\n--- Exercises 10 ---")
# 10a. Reconstruct A from its SVD components and confirm it matches
#      the original (use np.allclose).
matrix_A_10a = np.array([[1, 2], [3, 4], [5, 6]])
U_10a, S_10a, Vt_10a = np.linalg.svd(matrix_A_10a)

S_full_10a = np.zeros(matrix_A_10a.shape)
np.fill_diagonal(S_full_10a, S_10a)
A_reconstructed_10a = U_10a @ S_full_10a @ Vt_10a

print("10a. Original A:\n", matrix_A_10a)
print("     Reconstructed A:\n", A_reconstructed_10a)
print("     Are they approximately equal?", np.allclose(matrix_A_10a, A_reconstructed_10a))

# 10b. Use SVD to compute a low-rank approximation of A by keeping
#      only the largest singular value. How close is it to A?
# Keep only the largest singular value
k = 1
S_approx = np.zeros(matrix_A_10a.shape)
S_approx[0, 0] = S_10a[0] # Only the first (largest) singular value

A_low_rank = U_10a @ S_approx @ Vt_10a

print("10b. Low-rank approximation of A (k=1):\n", A_low_rank)
print("     Original A:\n", matrix_A_10a)
print("     Difference (A - A_low_rank):\n", matrix_A_10a - A_low_rank)
print("     Frobenius norm of the difference (closeness):\n", np.linalg.norm(matrix_A_10a - A_low_rank))


if __name__ == "__main__":
    example_create_arrays()
    example_matrix_multiplication()
    example_transpose()
    example_determinant()
    example_inverse()
    example_solve_linear_system()
    example_eigen()
    example_norms()
    example_rank()
    example_svd()



--- Exercises 1 ---
1a. 4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
1b. 3x3 Matrix filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
1c. Vector of 10 evenly spaced numbers between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

--- Exercises 2 ---
2a. A@B for given matrices:
 [[2 4]
 [6 8]]
2b. Product of 3x2 and 2x4 matrices:
 [[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]
    Shape of the result:
 (3, 4)

--- Exercises 3 ---
3a. Original 3x5 matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
    Transpose of 3x5 matrix:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
    Shape of transpose:
 (5, 3)
3b. (A @ B).T:
 [[ 27  61  95]
 [ 30  68 106]
 [ 33  75 117]]
    B.T @ A.T:
 [[ 27  61  95]
 [ 30  68 106]
 [ 33  75 117]]
    Are they equal? True

--- Exercises 4 ---
4a. Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]
    Determinant:
 0.9999999999999964
4b. Sing