<a href="https://colab.research.google.com/github/saikritikaboorla/Nasscom/blob/main/Assignment_7-Agriculture_5E0_NASSCOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Agriculture Case Study**

In [22]:
import pandas as pd

data = {
    'Day': [1, 2, 3, 4, 5, 6],
    'Soil Moisture': [72, 68, 62, 55, 48, 40],
    'Temperature': [27, 29, 31, 33, 35, 37],
    'Humidity': [78, 74, 70, 65, 60, 55],
    'Nitrogen': [48, 46, 43, 39, 35, 30],
    'Crop Health': [94, 90, 84, 76, 65, 52]
}

df = pd.DataFrame(data)
display(df.head())

,Day,Soil Moisture,Temperature,Humidity,Nitrogen,Crop Health
0,1,72,27,78,48,94
1,2,68,29,74,46,90
2,3,62,31,70,43,84
3,4,55,33,65,39,76
4,5,48,35,60,35,65


Task 1 — Analysis Using Python Basics
Store the crop-monitoring readings using appropriate Python data structures, then perform the following tasks.
1. Display the Crop Readings
Use a for loop to display all readings.
2. Identify Low Soil Moisture
If Soil Moisture < 50%, display “Low Soil Moisture Alert”. Otherwise, display “Soil Moisture Normal”.
3. Identify High Temperature
If Temperature > 35°C, display “High Temperature Alert”. Otherwise, display “Temperature Normal”.
4. Create a Function
Create crop_status(score) that returns: Healthy (score > 80), Under Stress (50 ≤ score ≤ 80), Critical (score < 50).


In [23]:
for index, row in df.iterrows():
    print(f"Day {int(row['Day'])}: Soil Moisture={row['Soil Moisture']}%, Temperature={row['Temperature']}°C, Humidity={row['Humidity']}%, Nitrogen={row['Nitrogen']} mg/kg, Crop Health={row['Crop Health']}%")

Day 1: Soil Moisture=72%, Temperature=27°C, Humidity=78%, Nitrogen=48 mg/kg, Crop Health=94%
Day 2: Soil Moisture=68%, Temperature=29°C, Humidity=74%, Nitrogen=46 mg/kg, Crop Health=90%
Day 3: Soil Moisture=62%, Temperature=31°C, Humidity=70%, Nitrogen=43 mg/kg, Crop Health=84%
Day 4: Soil Moisture=55%, Temperature=33°C, Humidity=65%, Nitrogen=39 mg/kg, Crop Health=76%
Day 5: Soil Moisture=48%, Temperature=35°C, Humidity=60%, Nitrogen=35 mg/kg, Crop Health=65%
Day 6: Soil Moisture=40%, Temperature=37°C, Humidity=55%, Nitrogen=30 mg/kg, Crop Health=52%


In [24]:
for index, row in df.iterrows():
    if row['Soil Moisture'] < 50:
        print(f"Day {int(row['Day'])}: Low Soil Moisture Alert")
    else:
        print(f"Day {int(row['Day'])}: Soil Moisture Normal")

Day 1: Soil Moisture Normal
Day 2: Soil Moisture Normal
Day 3: Soil Moisture Normal
Day 4: Soil Moisture Normal
Day 5: Low Soil Moisture Alert
Day 6: Low Soil Moisture Alert


In [25]:
for index, row in df.iterrows():
    if row['Temperature'] > 35:
        print(f"Day {int(row['Day'])}: High Temperature Alert")
    else:
        print(f"Day {int(row['Day'])}: Temperature Normal")

Day 1: Temperature Normal
Day 2: Temperature Normal
Day 3: Temperature Normal
Day 4: Temperature Normal
Day 5: Temperature Normal
Day 6: High Temperature Alert


In [26]:
def crop_status(score):
    if score > 80:
        return "Healthy"
    elif 50 <= score <= 80:
        return "Under Stress"
    else:
        return "Critical"

for index, row in df.iterrows():
    health_score = row['Crop Health']
    status = crop_status(health_score)
    print(f"Day {int(row['Day'])} Crop Health Score: {health_score}%, Status: {status}")

Day 1 Crop Health Score: 94%, Status: Healthy
Day 2 Crop Health Score: 90%, Status: Healthy
Day 3 Crop Health Score: 84%, Status: Healthy
Day 4 Crop Health Score: 76%, Status: Under Stress
Day 5 Crop Health Score: 65%, Status: Under Stress
Day 6 Crop Health Score: 52%, Status: Under Stress


Task 2 — Analysis Using NumPy
Convert the crop data into a NumPy array. The columns represent [Soil Moisture, Temperature, Humidity, Nitrogen, Crop Health].
Find the shape of the array and determine rows and columns.
Calculate the average of each parameter.
Find maximum temperature, minimum soil moisture, maximum humidity, minimum nitrogen, and minimum crop health.
Extract the soil moisture column as a NumPy vector.
Find all rows satisfying Temperature > 35°C.
Find all rows satisfying Soil Moisture < 50%.


In [27]:
import numpy as np

crop_data_np = df[['Soil Moisture', 'Temperature', 'Humidity', 'Nitrogen', 'Crop Health']].to_numpy()
print("Crop data as NumPy array:")
print(crop_data_np)

Crop data as NumPy array:
[[72 27 78 48 94]
 [68 29 74 46 90]
 [62 31 70 43 84]
 [55 33 65 39 76]
 [48 35 60 35 65]
 [40 37 55 30 52]]


In [28]:
array_shape = crop_data_np.shape
rows = array_shape[0]
cols = array_shape[1]
print(f"Shape of the array: {array_shape}")
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")

Shape of the array: (6, 5)
Number of rows: 6
Number of columns: 5


In [29]:
averages = np.mean(crop_data_np, axis=0)
print("Average of each parameter:")
print(f"  Soil Moisture: {averages[0]:.2f}")
print(f"  Temperature: {averages[1]:.2f}")
print(f"  Humidity: {averages[2]:.2f}")
print(f"  Nitrogen: {averages[3]:.2f}")
print(f"  Crop Health: {averages[4]:.2f}")

Average of each parameter:
  Soil Moisture: 57.50
  Temperature: 32.00
  Humidity: 67.00
  Nitrogen: 40.17
  Crop Health: 76.83


In [30]:
max_temperature = np.max(crop_data_np[:, 1])
min_soil_moisture = np.min(crop_data_np[:, 0])
max_humidity = np.max(crop_data_np[:, 2])
min_nitrogen = np.min(crop_data_np[:, 3])
min_crop_health = np.min(crop_data_np[:, 4])

print(f"Maximum Temperature: {max_temperature}")
print(f"Minimum Soil Moisture: {min_soil_moisture}")
print(f"Maximum Humidity: {max_humidity}")
print(f"Minimum Nitrogen: {min_nitrogen}")
print(f"Minimum Crop Health: {min_crop_health}")

Maximum Temperature: 37
Minimum Soil Moisture: 40
Maximum Humidity: 78
Minimum Nitrogen: 30
Minimum Crop Health: 52


In [31]:
soil_moisture_vector = crop_data_np[:, 0]
print("Soil Moisture vector:")
print(soil_moisture_vector)

Soil Moisture vector:
[72 68 62 55 48 40]


In [32]:
high_temp_rows = crop_data_np[crop_data_np[:, 1] > 35]
print("Rows with Temperature > 35°C:")
print(high_temp_rows)

Rows with Temperature > 35°C:
[[40 37 55 30 52]]


In [33]:
low_moisture_rows = crop_data_np[crop_data_np[:, 0] < 50]
print("Rows with Soil Moisture < 50%:")
print(low_moisture_rows)

Rows with Soil Moisture < 50%:
[[48 35 60 35 65]
 [40 37 55 30 52]]


Task 3 — Analysis Using Linear Algebra
The agriculture system uses soil moisture and temperature to calculate a simplified Crop Stress Index.
Let A = [[2, 1], [1, 3]] and X = [[55], [33]]. Calculate Y = AX and the resulting vector Y.
Additional Linear Algebra Tasks: For matrix A, find (1) transpose Aᵀ, (2) determinant det(A), and (3) inverse A⁻¹, if it exists.
Solving a System of Equations
Solve: 2x + y = 100 and x + 3y = 120. Write the equations in matrix form AX = B and use NumPy to solve for x and y.


In [34]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
X = np.array([[55], [33]])

Y = A @ X
print("Matrix A:")
print(A)
print("Matrix X:")
print(X)
print("Resulting vector Y = AX:")
print(Y)

Matrix A:
[[2 1]
 [1 3]]
Matrix X:
[[55]
 [33]]
Resulting vector Y = AX:
[[143]
 [154]]


In [35]:
A = np.array([[2, 1], [1, 3]])

transpose_A = A.T
determinant_A = np.linalg.det(A)
inverse_A = np.linalg.inv(A)

print("Transpose of A (Aᵀ):")
print(transpose_A)
print("Determinant of A (det(A)):")
print(determinant_A)
print("Inverse of A (A⁻¹):")
print(inverse_A)

Transpose of A (Aᵀ):
[[2 1]
 [1 3]]
Determinant of A (det(A)):
5.000000000000001
Inverse of A (A⁻¹):
[[ 0.6 -0.2]
 [-0.2  0.4]]


In [36]:
A_system = np.array([[2, 1], [1, 3]])
B_system = np.array([100, 120])

solution = np.linalg.solve(A_system, B_system)

x = solution[0]
y = solution[1]

print("System of equations: 2x + y = 100, x + 3y = 120")
print("Matrix A for system:")
print(A_system)
print("Vector B for system:")
print(B_system)
print("Solution for x and y:")
print(f"x = {x:.2f}")
print(f"y = {y:.2f}")

System of equations: 2x + y = 100, x + 3y = 120
Matrix A for system:
[[2 1]
 [1 3]]
Vector B for system:
[100 120]
Solution for x and y:
x = 36.00
y = 28.00


Task 4 — Analysis Using Calculus
The crop health score is modeled as H(t) = 100 − 3t − ½t², where H(t) represents crop health and t represents the number of days.
1. Differentiate H(t) and determine dH/dt.
2. Calculate dH/dt at t = 2 and t = 5.
3. Interpret whether crop health is decreasing at a constant, increasing, or decreasing rate.
Final Analysis and Decision
On which day does soil moisture first fall below 50%?
Calculate the total reduction in crop health.
Calculate the average of all monitored parameters.
Calculate Y = AX and solve AX = B.
Analyze crop-health deterioration using dH/dt.
Select APPROVE, MONITOR, or INTERVENE based on the analysis.


In [37]:
def H(t_val):
    return 100 - 3 * t_val - 0.5 * t_val**2

def dH_dt(t_val):
    return -3 - t_val

print("Crop health score model: H(t) = 100 - 3t - ½t²")
print("Differentiated H(t): dH/dt = -3 - t")

Crop health score model: H(t) = 100 - 3t - ½t²
Differentiated H(t): dH/dt = -3 - t


In [38]:
t_2 = 2
t_5 = 5

def dH_dt(t_val):
    return -3 - t_val

dH_dt_at_2 = dH_dt(t_2)
dH_dt_at_5 = dH_dt(t_5)

print(f"dH/dt at t = {t_2}: {dH_dt_at_2}")
print(f"dH/dt at t = {t_5}: {dH_dt_at_5}")

dH/dt at t = 2: -5
dH/dt at t = 5: -8


In [39]:
def dH_dt(t_val):
    return -3 - t_val

second_derivative = -1

print("Interpretation of crop health rate:")
print("The first derivative dH/dt = -3 - t. As 't' (days) increases, dH/dt becomes more negative.")
print("The second derivative d²H/dt² = -1 (a constant negative value).")
print("This indicates that crop health is decreasing at an *increasing* rate (getting worse faster over time).")

Interpretation of crop health rate:
The first derivative dH/dt = -3 - t. As 't' (days) increases, dH/dt becomes more negative.
The second derivative d²H/dt² = -1 (a constant negative value).
This indicates that crop health is decreasing at an *increasing* rate (getting worse faster over time).


In [40]:
import numpy as np

soil_moisture_below_50_day = df[df['Soil Moisture'] < 50]['Day'].min()
print(f"On which day does soil moisture first fall below 50%: Day {int(soil_moisture_below_50_day)}")

total_reduction_crop_health = df['Crop Health'].iloc[0] - df['Crop Health'].iloc[-1]
print(f"Total reduction in crop health: {total_reduction_crop_health}%")

numerical_cols = ['Soil Moisture', 'Temperature', 'Humidity', 'Nitrogen', 'Crop Health']

averages = np.mean(df[numerical_cols], axis=0)
print("Average of all monitored parameters:")
print(f"  Soil Moisture: {averages[0]:.2f}")
print(f"  Temperature: {averages[1]:.2f}")
print(f"  Humidity: {averages[2]:.2f}")
print(f"  Nitrogen: {averages[3]:.2f}")
print(f"  Crop Health: {averages[4]:.2f}")

print("Based on the analysis:")
print("- Soil moisture drops below 50% on Day 5 and continues to decrease.")
print("- Temperature is steadily increasing, reaching high alert on Day 6.")
print("- Crop health is consistently decreasing and the rate of decrease is accelerating.")

current_crop_health_status = df['Crop Health'].iloc[-1]
if current_crop_health_status < 50:
    decision = "INTERVENE"
elif 50 <= current_crop_health_status <= 80:
    decision = "MONITOR"
else:
    decision = "APPROVE"

print(f"Overall decision: {decision}")

On which day does soil moisture first fall below 50%: Day 5
Total reduction in crop health: 42%
Average of all monitored parameters:
  Soil Moisture: 57.50
  Temperature: 32.00
  Humidity: 67.00
  Nitrogen: 40.17
  Crop Health: 76.83
Based on the analysis:
- Soil moisture drops below 50% on Day 5 and continues to decrease.
- Temperature is steadily increasing, reaching high alert on Day 6.
- Crop health is consistently decreasing and the rate of decrease is accelerating.
Overall decision: MONITOR


/tmp/ipykernel_1316/2014542278.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"  Soil Moisture: {averages[0]:.2f}")
/tmp/ipykernel_1316/2014542278.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"  Temperature: {averages[1]:.2f}")
/tmp/ipykernel_1316/2014542278.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"  Humidity: {averages[2]:.2f}")
/tmp/ipykernel_1316/2014542278.py:16: FutureWarning: Ser