<a href="https://colab.research.google.com/github/saikritikaboorla/Nasscom/blob/main/Assignment_8-Healthcare_5E0_NASSCOM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Healthcare Case Study**

In [1]:
import pandas as pd

data = {
    'Time (h)': [0, 1, 2, 3, 4, 5],
    'Heart Rate': [76, 82, 90, 98, 105, 112],
    'Temperature': [36.7, 37.0, 37.4, 38.0, 38.5, 39.0],
    'SpO₂': [98, 97, 96, 94, 92, 89],
    'Systolic BP': [122, 125, 130, 135, 140, 148],
    'Health Score': [92, 88, 82, 74, 65, 52]
}

df = pd.DataFrame(data)
display(df.head())

,Time (h),Heart Rate,Temperature,SpO₂,Systolic BP,Health Score
0,0,76,36.7,98,122,92
1,1,82,37.0,97,125,88
2,2,90,37.4,96,130,82
3,3,98,38.0,94,135,74
4,4,105,38.5,92,140,65


Task 1 — Analysis Using Python Basics
Store the patient readings using appropriate Python data structures, then perform the following tasks.
1. Display the Patient Readings
Use a for loop to display all patient readings.
2. Identify High Temperature
If Temperature > 38°C, display “High Temperature Alert”. Otherwise, display “Temperature Normal”.
3. Identify Low Oxygen Level
If SpO₂ < 90%, display “Low Oxygen Alert”. Otherwise, display “Oxygen Level Normal”.
4. Create a Function
Create health_status(score) that returns: Healthy (score > 80), Monitor (50 ≤ score ≤ 80), Critical (score < 50).


### Task 1.1: Display Patient Readings

In [2]:
for index, row in df.iterrows():
    print(f"Time: {row['Time (h)']:.0f}h, Heart Rate: {row['Heart Rate']:.0f} BPM, Temperature: {row['Temperature']:.1f}°C, SpO₂: {row['SpO₂']:.0f}%, Systolic BP: {row['Systolic BP']:.0f} mmHg, Health Score: {row['Health Score']:.0f}%")

Time: 0h, Heart Rate: 76 BPM, Temperature: 36.7°C, SpO₂: 98%, Systolic BP: 122 mmHg, Health Score: 92%
Time: 1h, Heart Rate: 82 BPM, Temperature: 37.0°C, SpO₂: 97%, Systolic BP: 125 mmHg, Health Score: 88%
Time: 2h, Heart Rate: 90 BPM, Temperature: 37.4°C, SpO₂: 96%, Systolic BP: 130 mmHg, Health Score: 82%
Time: 3h, Heart Rate: 98 BPM, Temperature: 38.0°C, SpO₂: 94%, Systolic BP: 135 mmHg, Health Score: 74%
Time: 4h, Heart Rate: 105 BPM, Temperature: 38.5°C, SpO₂: 92%, Systolic BP: 140 mmHg, Health Score: 65%
Time: 5h, Heart Rate: 112 BPM, Temperature: 39.0°C, SpO₂: 89%, Systolic BP: 148 mmHg, Health Score: 52%


### Task 1.2: Identify High Temperature

In [3]:
for temp in df['Temperature']:
    if temp > 38:
        print(f"High Temperature Alert: {temp}°C")
    else:
        print(f"Temperature Normal: {temp}°C")

Temperature Normal: 36.7°C
Temperature Normal: 37.0°C
Temperature Normal: 37.4°C
Temperature Normal: 38.0°C
High Temperature Alert: 38.5°C
High Temperature Alert: 39.0°C


### Task 1.3: Identify Low Oxygen Level

In [4]:
for spo2 in df['SpO₂']:
    if spo2 < 90:
        print(f"Low Oxygen Alert: {spo2}%")
    else:
        print(f"Oxygen Level Normal: {spo2}%")

Oxygen Level Normal: 98%
Oxygen Level Normal: 97%
Oxygen Level Normal: 96%
Oxygen Level Normal: 94%
Oxygen Level Normal: 92%
Low Oxygen Alert: 89%


### Task 1.4: Create a Health Status Function

In [5]:
def health_status(score):
    if score > 80:
        return "Healthy"
    elif 50 <= score <= 80:
        return "Monitor"
    else:
        return "Critical"

print(f"Health status for score 92: {health_status(92)}")
print(f"Health status for score 74: {health_status(74)}")
print(f"Health status for score 52: {health_status(52)}")
print(f"Health status for score 45: {health_status(45)}")

Health status for score 92: Healthy
Health status for score 74: Monitor
Health status for score 52: Monitor
Health status for score 45: Critical


Task 2 — Analysis Using NumPy
Convert the patient data into a NumPy array. The columns represent [Heart Rate, Temperature, SpO₂, Systolic BP, Health Score].
Find the shape of the array and determine rows and columns.
Calculate the average of each parameter.
Find maximum heart rate, minimum SpO₂, maximum temperature, maximum systolic BP, and minimum health score.
Extract the SpO₂ column as a NumPy vector.
Find all rows satisfying Heart Rate > 100 BPM.
Find all rows satisfying SpO₂ < 90%.


### Task 2.1: Convert to NumPy Array and Find Shape

In [6]:
import numpy as np

patient_data_np = df[['Heart Rate', 'Temperature', 'SpO₂', 'Systolic BP', 'Health Score']].to_numpy()
print("NumPy Array:\n", patient_data_np)
print("Shape of the array:", patient_data_np.shape)
print("Number of rows:", patient_data_np.shape[0])
print("Number of columns:", patient_data_np.shape[1])

NumPy Array:
 [[ 76.   36.7  98.  122.   92. ]
 [ 82.   37.   97.  125.   88. ]
 [ 90.   37.4  96.  130.   82. ]
 [ 98.   38.   94.  135.   74. ]
 [105.   38.5  92.  140.   65. ]
 [112.   39.   89.  148.   52. ]]
Shape of the array: (6, 5)
Number of rows: 6
Number of columns: 5


### Task 2.2: Calculate Averages of Each Parameter

In [7]:
average_heart_rate = np.mean(patient_data_np[:, 0])
average_temperature = np.mean(patient_data_np[:, 1])
average_spo2 = np.mean(patient_data_np[:, 2])
average_systolic_bp = np.mean(patient_data_np[:, 3])
average_health_score = np.mean(patient_data_np[:, 4])

print(f"Average Heart Rate: {average_heart_rate:.2f}")
print(f"Average Temperature: {average_temperature:.2f}")
print(f"Average SpO₂: {average_spo2:.2f}")
print(f"Average Systolic BP: {average_systolic_bp:.2f}")
print(f"Average Health Score: {average_health_score:.2f}")

Average Heart Rate: 93.83
Average Temperature: 37.77
Average SpO₂: 94.33
Average Systolic BP: 133.33
Average Health Score: 75.50


### Task 2.3: Find Max/Min Values

In [8]:
max_heart_rate = np.max(patient_data_np[:, 0])
min_spo2 = np.min(patient_data_np[:, 2])
max_temperature = np.max(patient_data_np[:, 1])
max_systolic_bp = np.max(patient_data_np[:, 3])
min_health_score = np.min(patient_data_np[:, 4])

print(f"Maximum Heart Rate: {max_heart_rate}")
print(f"Minimum SpO₂: {min_spo2}")
print(f"Maximum Temperature: {max_temperature}")
print(f"Maximum Systolic BP: {max_systolic_bp}")
print(f"Minimum Health Score: {min_health_score}")

Maximum Heart Rate: 112.0
Minimum SpO₂: 89.0
Maximum Temperature: 39.0
Maximum Systolic BP: 148.0
Minimum Health Score: 52.0


### Task 2.4: Extract SpO₂ Column

In [9]:
spo2_vector = patient_data_np[:, 2]
print("SpO₂ Vector:", spo2_vector)

SpO₂ Vector: [98. 97. 96. 94. 92. 89.]


### Task 2.5: Find Rows with Heart Rate > 100 BPM

In [10]:
high_heart_rate_rows = patient_data_np[patient_data_np[:, 0] > 100]
print("Rows with Heart Rate > 100 BPM:\n", high_heart_rate_rows)

Rows with Heart Rate > 100 BPM:
 [[105.   38.5  92.  140.   65. ]
 [112.   39.   89.  148.   52. ]]


### Task 2.6: Find Rows with SpO₂ < 90%

In [11]:
low_oxygen_rows = patient_data_np[patient_data_np[:, 2] < 90]
print("Rows with SpO₂ < 90%:\n", low_oxygen_rows)

Rows with SpO₂ < 90%:
 [[112.  39.  89. 148.  52.]]


Task 3 — Analysis Using Linear Algebra
The hospital uses a simplified Patient Risk Index based on heart rate and temperature.
Let A = [[2, 1], [1, 3]] and X = [[98], [38]]. Calculate Y = AX and the resulting vector Y.
Additional Linear Algebra Tasks: For matrix A, find (1) transpose Aᵀ, (2) determinant det(A), and (3) inverse A⁻¹, if it exists.
Solving a System of Equations
Solve: 2x + y = 100 and x + 3y = 120. Write the equations in matrix form AX = B and use NumPy to solve for x and y.


### Task 3.1: Calculate Patient Risk Index Y = AX

In [12]:
import numpy as np

A = np.array([[2, 1], [1, 3]])
X = np.array([[98], [38]])

Y = np.dot(A, X)

print("Matrix A:\n", A)
print("Matrix X:\n", X)
print("Resulting vector Y (AX):\n", Y)

Matrix A:
 [[2 1]
 [1 3]]
Matrix X:
 [[98]
 [38]]
Resulting vector Y (AX):
 [[234]
 [212]]


### Task 3.2: Additional Linear Algebra Tasks for Matrix A

In [13]:
A_transpose = A.T
det_A = np.linalg.det(A)

print("Transpose of A (Aᵀ):\n", A_transpose)
print("Determinant of A (det(A)):", det_A)

if det_A != 0:
    A_inverse = np.linalg.inv(A)
    print("Inverse of A (A⁻¹):\n", A_inverse)
else:
    print("Inverse of A does not exist as determinant is zero.")

Transpose of A (Aᵀ):
 [[2 1]
 [1 3]]
Determinant of A (det(A)): 5.000000000000001
Inverse of A (A⁻¹):
 [[ 0.6 -0.2]
 [-0.2  0.4]]


### Task 3.3: Solving a System of Equations (AX = B)

In [14]:
A_eq = np.array([[2, 1], [1, 3]])
B_eq = np.array([[100], [120]])

x_y_solution = np.linalg.solve(A_eq, B_eq)

print("Matrix A for equations:\n", A_eq)
print("Matrix B for equations:\n", B_eq)
print("Solution for x and y (x, y):\n", x_y_solution)

Matrix A for equations:
 [[2 1]
 [1 3]]
Matrix B for equations:
 [[100]
 [120]]
Solution for x and y (x, y):
 [[36.]
 [28.]]


Task 4 — Analysis Using Calculus
The patient's health score is modeled as H(t) = 100 − 4t − ½t², where H(t) is the health score and t is time in hours.
1. Differentiate H(t) and determine dH/dt.
2. Calculate dH/dt at t = 2 and t = 5.
3. Interpret whether the health score is decreasing at a constant, increasing, or decreasing rate.


### Task 4.1: Differentiate H(t) and Determine dH/dt

In [15]:
import sympy
from sympy import symbols, diff

t = symbols('t')
H_t = 100 - 4*t - (1/2)*t**2
dH_dt = diff(H_t, t)

print(f"H(t) = {H_t}")
print(f"dH/dt = {dH_dt}")

H(t) = -0.5*t**2 - 4*t + 100
dH/dt = -1.0*t - 4


### Task 4.2: Calculate dH/dt at t = 2 and t = 5

In [16]:
dH_dt_at_2 = dH_dt.subs(t, 2)
dH_dt_at_5 = dH_dt.subs(t, 5)

print(f"dH/dt at t = 2: {dH_dt_at_2}")
print(f"dH/dt at t = 5: {dH_dt_at_5}")

dH/dt at t = 2: -6.00000000000000
dH/dt at t = 5: -9.00000000000000


### Task 4.3: Interpret the Rate of Health Score Change

In [17]:
if dH_dt.is_constant():
    rate_type = "constant"
elif diff(dH_dt, t) > 0:
    rate_type = "increasing"
elif diff(dH_dt, t) < 0:
    rate_type = "decreasing"
else:
    rate_type = "varying"

print(f"The health score is decreasing at a {rate_type} rate, as dH/dt is a linear function of t, specifically -4 - t, which becomes more negative as t increases.")

The health score is decreasing at a decreasing rate, as dH/dt is a linear function of t, specifically -4 - t, which becomes more negative as t increases.


Final Analysis and Decision
At what time does the temperature first exceed 38°C?
What is the total reduction in health score?
Calculate all parameter averages.
Calculate Y = AX and solve AX = B.
Analyze the health-score rate using dH/dt.
Select NORMAL, MONITOR, or CRITICAL based on the analysis.


### Final Analysis: Temperature Exceeding 38°C

In [18]:
time_exceed_38 = df[df['Temperature'] > 38]['Time (h)'].min()
print(f"The temperature first exceeds 38°C at Time (h): {time_exceed_38}")

The temperature first exceeds 38°C at Time (h): 4


### Final Analysis: Total Reduction in Health Score

In [19]:
initial_health_score = df['Health Score'].iloc[0]
final_health_score = df['Health Score'].iloc[-1]
total_reduction_health_score = initial_health_score - final_health_score
print(f"Total reduction in health score: {total_reduction_health_score}")

Total reduction in health score: 40


### Final Analysis: Calculate All Parameter Averages

In [20]:
average_parameters = df.mean(numeric_only=True)
print("Average of all parameters:\n", average_parameters)

Average of all parameters:
 Time (h)          2.500000
Heart Rate       93.833333
Temperature      37.766667
SpO₂             94.333333
Systolic BP     133.333333
Health Score     75.500000
dtype: float64


### Final Analysis: Calculate Y = AX and Solve AX = B

In [21]:
import numpy as np

# Recalculate Y = AX from Task 3.1
A_risk = np.array([[2, 1], [1, 3]])
X_risk = np.array([[df['Heart Rate'].iloc[-1]], [df['Temperature'].iloc[-1]]]) # Using latest values
Y_calculated = np.dot(A_risk, X_risk)
print("Calculated Patient Risk Index Y (based on latest HR and Temp):\n", Y_calculated)

# Recalculate solution for AX = B from Task 3.3
A_eq_final = np.array([[2, 1], [1, 3]])
B_eq_final = np.array([[100], [120]])
solution_x_y_final = np.linalg.solve(A_eq_final, B_eq_final)
print("Solution for system of equations (x, y):\n", solution_x_y_final)

Calculated Patient Risk Index Y (based on latest HR and Temp):
 [[263.]
 [229.]]
Solution for system of equations (x, y):
 [[36.]
 [28.]]


### Final Analysis: Analyze the Health-Score Rate Using dH/dt

In [22]:
import sympy
from sympy import symbols, diff

t_sym = symbols('t')
H_t_final = 100 - 4*t_sym - (1/2)*t_sym**2
dH_dt_final = diff(H_t_final, t_sym)

# Evaluate dH/dt at the last time point (t=5)
dH_dt_at_last_t = dH_dt_final.subs(t_sym, df['Time (h)'].iloc[-1])

print(f"The health score model is H(t) = {H_t_final}")
print(f"The rate of change of health score is dH/dt = {dH_dt_final}")
print(f"At the last recorded time (t={df['Time (h)'].iloc[-1]}h), dH/dt = {dH_dt_at_last_t}. This indicates a significant and accelerating decrease in health score.")

The health score model is H(t) = -0.5*t**2 - 4*t + 100
The rate of change of health score is dH/dt = -1.0*t - 4
At the last recorded time (t=5h), dH/dt = -9.00000000000000. This indicates a significant and accelerating decrease in health score.


### Final Analysis: Select NORMAL, MONITOR, or CRITICAL

In [23]:
def health_status_final(score):
    if score > 80:
        return "Normal"
    elif 50 <= score <= 80:
        return "Monitor"
    else:
        return "Critical"

last_health_score = df['Health Score'].iloc[-1]
patient_condition = health_status_final(last_health_score)

print(f"Based on the latest Health Score of {last_health_score}%, the patient's condition is: {patient_condition}")

has_high_temp = any(df['Temperature'] > 38)
has_low_spo2 = any(df['SpO₂'] < 90)

if patient_condition == "Critical" or has_low_spo2 or dH_dt_at_last_t < -8:
    overall_status = "CRITICAL"
elif patient_condition == "Monitor" or has_high_temp or dH_dt_at_last_t < -5:
    overall_status = "MONITOR"
else:
    overall_status = "NORMAL"

print(f"Overall Patient Status considering all parameters: {overall_status}")

Based on the latest Health Score of 52%, the patient's condition is: Monitor
Overall Patient Status considering all parameters: CRITICAL
